# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/threadweaver': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'kdevelop/kdevelop': '@same'
