/*
    SPDX-FileCopyrightText: 2012 Sven Brauch <svenbrauch@googlemail.com>

    SPDX-License-Identifier: LGPL-2.0-or-later
*/

#ifndef KDEVPYTHON_VERSION_H
#define KDEVPYTHON_VERSION_H

#define PYTHON_VERSION_MINOR @Python3_VERSION_MINOR@
#define PYTHON_VERSION_MINOR_STR "@Python3_VERSION_MINOR@"

#define PYTHON_VERSION_MAJOR @Python3_VERSION_MAJOR@
#define PYTHON_VERSION_MAJOR_STR "@Python3_VERSION_MAJOR@"

#define PYTHON_VERSION QT_VERSION_CHECK(@Python3_VERSION_MAJOR@, @Python3_VERSION_MINOR@, @Python3_VERSION_PATCH@)
#define PYTHON_VERSION_STR "@Python3_VERSION_MAJOR@.@Python3_VERSION_MINOR@"

#define PYTHON_EXECUTABLE "@Python3_EXECUTABLE@"

#endif
