[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=Python Language Support (Python 3 version)
Comment[ca]=Implementació del llenguatge Python (versió 3 del Python)
Comment[de]=Sprachunterstützung für Python Version 3
Comment[en_GB]=Python Language Support (Python 3 version)
Comment[es]=Implementación del lenguaje Python (versión 3 de Python)
Comment[fi]=Python-kielituki (Python 3)
Comment[it]=Supporto per il linguaggio Python (Python 3)
Comment[nl]=Ondersteuning voor de taal Python (Python versie 3)
Comment[pl]=Obsługa języka Python (Python w wersji 3)
Comment[pt]=Suporte para a Linguagem Python (versão 3)
Comment[pt_BR]=Suporte à linguagem Python (versão Python 3)
Comment[sk]=Podpora jazyka Python (verzia Python 3)
Comment[sl]=Podpora jeziku Python (različica Python 3)
Comment[uk]=Підтримка мови Python (версія Python 3)
Comment[x-test]=xxPython Language Support (Python 3 version)xx
Name=Python Support (Python 3 version)
Name[ca]=Implementació de Python (versió 3 del Python)
Name[de]=Unterstützung für Python Version 3
Name[en_GB]=Python Support (Python 3 version)
Name[es]=Implementación de Python (versión 3 de Python)
Name[fi]=Python-tuki (Python 3)
Name[it]=Supporto per Python (Python 3)
Name[nl]=Ondersteuning voor Python (Python versie 3)
Name[pl]=Obsługa Pythona (Python w wersji 3)
Name[pt]=Suporte para Python (versão 3)
Name[pt_BR]=Suporte à Python (versão Python 3)
Name[sk]=Podpora Pythonu (verzia Python 3)
Name[sl]=Podpora za Python (različica Python 3)
Name[uk]=Підтримка Python (версія Python 3)
Name[x-test]=xxPython Support (Python 3 version)xx
GenericName=Python Support (Python 3 version)
GenericName[ca]=Implementació de Python (versió 3 del Python)
GenericName[de]=Unterstützung für Python Version 3
GenericName[en_GB]=Python Support (Python 3 version)
GenericName[es]=Implementación de Python (versión 3 de Python)
GenericName[fi]=Python-tuki (Python 3)
GenericName[it]=Supporto per Python (Python 3)
GenericName[nl]=Ondersteuning voor Python (Python versie 3)
GenericName[pl]=Obsługa Pythona (Python w wersji 3)
GenericName[pt]=Suporte para Python (versão 3)
GenericName[pt_BR]=Suporte à Python (versão Python 3)
GenericName[sk]=Podpora Pythonu (verzia Python 3)
GenericName[sl]=Podpora za Python (različica Python 3)
GenericName[uk]=Підтримка Python (версія Python 3)
GenericName[x-test]=xxPython Support (Python 3 version)xx
ServiceTypes=KDevelop/Plugin
Icon=text-x-python
X-KDE-Library=kdevpythonlanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=Python
X-KDevelop-Args=PYTHON
X-KDevelop-Interfaces=ILanguageSupport,org.kdevelop.ILanguageCheckProvider
X-KDevelop-SupportedMimeTypes=text/x-python
X-KDE-PluginInfo-Name=kdevpythonsupport
X-KDevelop-Mode=NoGUI
X-KDE-PluginInfo-Category=Language Support
