#ifndef PYTHONCOMPLETIONEXPORT_H
#define PYTHONCOMPLETIONEXPORT_H

/* needed for KDE_EXPORT macros */
#include <kdemacros.h>


#ifndef KDEVPYTHONCOMPLETION_EXPORT
# ifdef MAKE_KDEV4PYTHONCOMPLETION_LIB
#  define KDEVPYTHONCOMPLETION_EXPORT KDE_EXPORT
# else
#  define KDEVPYTHONCOMPLETION_EXPORT KDE_IMPORT
# endif
#endif

#endif